name: Dependabot PR Comment

on:
  pull_request_target:
    types: [opened]

jobs:
  dependabot-comment:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            const message = `Hello World!`;
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: message
            });